"""Updated CompletedActivity model

Revision ID: 806e3ab83343
Revises: a5f26e9f9eab
Create Date: 2025-02-05 15:13:34.302009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806e3ab83343'
down_revision = 'a5f26e9f9eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_completed_activities_course_id'), ['course_id'], unique=False)
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_completed_activities_course_id'))
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
