"""Updated course model

Revision ID: a5f26e9f9eab
Revises: 46564e94cd06
Create Date: 2025-02-04 21:55:08.591904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f26e9f9eab'
down_revision = '46564e94cd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisites', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('media_url')
        batch_op.drop_column('prerequisites')

    # ### end Alembic commands ###
